import type { Metadata } from "next"
import Navbar from "@/components/navbar/Navbar"
import { Inter } from "next/font/google"

const inter = Inter({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Search for visas",
  description: "Generated by create next app",
}

export default function VisasLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body
        className={`${inter.className} flex min-h-screen flex-col items-center`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
